# Generated by Django 3.1.7 on 2021-04-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0002_auto_20210413_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='email',
        ),
    ]
