# Generated by Django 3.1.7 on 2021-04-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0004_uploader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uploader',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['date', 'time']},
        ),
    ]
